### ISSUE TITLE
switch to using Sinatra::Base#settings?

### ISSUE THREAD

**Issue by cactus** [rtomayko/sinatra-sequel#5]
warning on recent versions of sinatra

    Sinatra::Base#options is deprecated and will be removed, use #settings insetad.

I can whip up a patch if you want, but it looks like the change is pretty straightforward... although I admit to not knowing how this would impact compatibility with older versions of sinatra.

**Comment by cactus** [comment]
old

**Comment by mwpastore** [comment]
@cactus: Why did you close this issue? It is still a problem with the current versions of `sinatra` and `sinatra-sequel`. 

```
Sinatra::Base#options is deprecated and will be removed, use #settings instead.
```

**Comment by cactus** [comment]
@mwpastore It was 4 years old with no feedback. I figured nobody cared so I closed it. Feel free to file a new issue I guess.

**Comment by dan** [comment]
This is still a problem.
